// ============================================================
// Auto-generated by scripts/sync-audio-manifest.mjs.
// Put fixed narration MP3 files in /public/audio using names like:
//   slide-01.mp3, slide-02.mp3, ...
// Files listed here are used before browser TTS, so the voice stays identical
// across PC, iPhone, Android, and every browser.
// ============================================================

export const AUDIO_MANIFEST: string[] = [];

export function hasAudio(key: string): boolean {
  return AUDIO_MANIFEST.includes(key);
}
