// ============================================================
// Auto-generated by scripts/sync-audio-manifest.mjs.
// Fixed narration MP3 files are read from /public/audio.
// Files listed here are used before browser TTS, so the voice stays identical
// across PC, iPhone, Android, and every browser.
// ============================================================

export const AUDIO_MANIFEST: string[] = [
  "ppt-activity-governance-or-compliance",
  "ppt-activity-governance-or-compliance-feedback-1-correct",
  "ppt-activity-governance-or-compliance-feedback-1-incorrect",
  "ppt-activity-governance-or-compliance-feedback-2-correct",
  "ppt-activity-governance-or-compliance-feedback-2-incorrect",
  "ppt-activity-governance-or-compliance-feedback-3-correct",
  "ppt-activity-governance-or-compliance-feedback-3-incorrect",
  "ppt-activity-governance-or-compliance-feedback-4-correct",
  "ppt-activity-governance-or-compliance-feedback-4-incorrect",
  "ppt-activity-governance-or-compliance-question-2",
  "ppt-activity-governance-or-compliance-question-3",
  "ppt-activity-governance-or-compliance-question-4",
  "ppt-conclusion",
  "ppt-conflict-scenario",
  "ppt-conflict-scenario-complete",
  "ppt-conflict-scenario-discussion-1",
  "ppt-conflict-scenario-discussion-2",
  "ppt-conflict-scenario-discussion-3",
  "ppt-conflict-scenario-question-2",
  "ppt-conflict-scenario-question-3",
  "ppt-ethics-conflict",
  "ppt-framework",
  "ppt-governance-compliance",
  "ppt-governance-models",
  "ppt-intro",
  "slide-01",
  "slide-02",
  "slide-03",
  "slide-04",
  "slide-05",
  "slide-06",
  "slide-07",
  "slide-08",
  "slide-09",
  "slide-10",
  "slide-11",
  "slide-12",
  "slide-13",
  "slide-14",
  "slide-15",
  "slide-16",
  "slide-17",
  "slide-18"
];

export function hasAudio(key: string): boolean {
  return AUDIO_MANIFEST.includes(key);
}
